app:
  build: ./
  working_dir: /project
  links:
    - mongo
  volumes:
    - ./:/project
  command: forever app.js -l app.log
  environment:
    NODE_ENV: 'production'
  ports:
    - "5000:5000"

dev:
  build: ./
  working_dir: /project
  links:
    - mongo
  volumes:
    - ./:/project
  command: node app.js
  environment:
    NODE_ENV: 'dev'
  ports:
    - "3000:3000"

mongo:
  image: mongo:latest
  command: "/entrypoint.sh mongod --smallfiles"
  ports:
    - "27017:27017"

mongocli:
  image: mongo:latest
  links:
    - mongo
  volumes:
    - ./:/project